AllCops:
  DisplayCopNames: true

require: rubocop-rspec

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

RSpec/NamedSubject:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

RSpec/NestedGroups:
  MaxNesting: 4
