AllCops:
  DisplayCopNames: true

require: rubocop-rspec

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Style/Documentation:
  Enabled: false

Style/EndOfLine:
  Enabled: false

Style/PercentLiteralDelimiters:
  # Specify the default preferred delimiter for all types with the 'default' key
  # Override individual delimiters (even with default specified) by specifying
  # an individual key
  PreferredDelimiters:
    default: ()
    '%i': ()
    '%I': ()
    '%r': '{}'
    '%w': ()
    '%W': ()

Metrics/LineLength:
  Max: 120

RSpec/NamedSubject:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

RSpec/NestedGroups:
  Max: 4
