sudo: false
language: ruby
cache:
  - bundler
rvm:
  - 2.1
  - 2.2
  - 2.3.3
  - 2.4.0
  - ruby-head

os:
  - linux
  - osx

matrix:
  allow_failures:
    - rvm: ruby-head

before_install: gem install bundler
after_success:
  - bundle exec codeclimate-test-reporter

addons:
  code_climate:
    repo_token: 22322d923b03d8476d20a367aac12ade706f39686d4fc08b9a19978276cb68f1
